# https://dart.dev/guides/language/analysis-options
# https://dart.dev/tools/linter-rules
# https://dart.dev/tools/linter-rules#flutter_lints
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_single_quotes
    - always_use_package_imports
    # - avoid_print
