name: notes_tasks
description: "A notes & tasks app."
publish_to: 'none'
version: 1.0.0+1
environment:
  # Appwrite was incompatible with the latest http package.
  # It also comes with some more outdated packages and seems to be written with sdk 2.12.0
  # I manually set the min sdk to 3.0.0 in order to have newer language features.
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sizer: ^2.0.15
  flutter_bloc: ^8.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dynamic_color: ^1.6.8
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  stream_transform: ^2.1.0
  bloc_concurrency: ^0.2.2
  appwrite: ^11.0.1
  go_router: ^12.1.1
  visibility_detector: ^0.4.0+2
  flutter_dotenv: ^5.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - .env
